# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cic-tools 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "cic-tools".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Leon Davis".freeze]
  s.date = "2018-11-23"
  s.description = "cic tools".freeze
  s.email = "info@lvl-up.uk".freeze
  s.executables = ["cic".freeze, "exercise".freeze]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "bin/cic",
    "bin/exercise",
    "lib/commands.rb",
    "lib/commands/cic.rb",
    "lib/commands/cic/command.rb",
    "lib/commands/cic/helpers.rb",
    "lib/commands/exercise/command.rb",
    "lib/commands/exercise/headless_browser_driver.rb",
    "lib/commands/exercise/instructions.rb",
    "lib/commands/exercise/output.rb",
    "lib/commands/exercise/output/ansible.rb",
    "lib/commands/exercise/output/cic.rb",
    "lib/commands/exercise/output/pytest.rb",
    "lib/commands/exercise/render_methods.rb",
    "lib/commands/track.rb",
    "lib/commands/track/command.rb",
    "lib/commands/track/errors.rb",
    "lib/commands/track/exercise.rb",
    "lib/commands/track/helpers.rb",
    "lib/commands/track/learning_track.rb",
    "lib/utils/commandline.rb",
    "lib/utils/commandline/output.rb",
    "lib/utils/commandline/return.rb",
    "lib/utils/docker.rb"
  ]
  s.homepage = "https://github.com/FidiletyInternational/cicimages-tools".freeze
  s.licenses = ["Apache 2.0".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.3".freeze)
  s.rubygems_version = "2.7.7".freeze
  s.summary = "cictools".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<git>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<json>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<netrc>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<octokit>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<thor>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<capybara>.freeze, ["= 2.15.2"])
      s.add_runtime_dependency(%q<chromedriver-helper>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<page_magic>.freeze, [">= 1.2.9"])
      s.add_runtime_dependency(%q<watir>.freeze, ["~> 6.1"])
      s.add_runtime_dependency(%q<i18n>.freeze, [">= 0"])
      s.add_development_dependency(%q<bump>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<mirage>.freeze, ["= 4.0.0.alpha10"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0"])
    else
      s.add_dependency(%q<colorize>.freeze, [">= 0"])
      s.add_dependency(%q<git>.freeze, [">= 0"])
      s.add_dependency(%q<json>.freeze, [">= 0"])
      s.add_dependency(%q<netrc>.freeze, [">= 0"])
      s.add_dependency(%q<octokit>.freeze, [">= 0"])
      s.add_dependency(%q<thor>.freeze, [">= 0"])
      s.add_dependency(%q<capybara>.freeze, ["= 2.15.2"])
      s.add_dependency(%q<chromedriver-helper>.freeze, [">= 0"])
      s.add_dependency(%q<page_magic>.freeze, [">= 1.2.9"])
      s.add_dependency(%q<watir>.freeze, ["~> 6.1"])
      s.add_dependency(%q<i18n>.freeze, [">= 0"])
      s.add_dependency(%q<bump>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<mirage>.freeze, ["= 4.0.0.alpha10"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<yard>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<colorize>.freeze, [">= 0"])
    s.add_dependency(%q<git>.freeze, [">= 0"])
    s.add_dependency(%q<json>.freeze, [">= 0"])
    s.add_dependency(%q<netrc>.freeze, [">= 0"])
    s.add_dependency(%q<octokit>.freeze, [">= 0"])
    s.add_dependency(%q<thor>.freeze, [">= 0"])
    s.add_dependency(%q<capybara>.freeze, ["= 2.15.2"])
    s.add_dependency(%q<chromedriver-helper>.freeze, [">= 0"])
    s.add_dependency(%q<page_magic>.freeze, [">= 1.2.9"])
    s.add_dependency(%q<watir>.freeze, ["~> 6.1"])
    s.add_dependency(%q<i18n>.freeze, [">= 0"])
    s.add_dependency(%q<bump>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<mirage>.freeze, ["= 4.0.0.alpha10"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<yard>.freeze, [">= 0"])
  end
end

