FROM lvlup/ci_course
RUN apt-get update -q -y

RUN apt-get -y -q install checkinstall tk-dev libgdbm-dev libncursesw5-dev libreadline-gplv2-dev libsqlite3-dev curl build-essential libbz2-dev libc6-dev bash wget unzip ca-certificates vim openssh-server openssl libffi-dev libssl-dev python3-dev python3-setuptools zlib1g-dev git && apt-get clean

RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc && echo 'eval "$(pyenv init -)"' >> ~/.bashrc

RUN ["/bin/bash", "-c", "PYENV_ROOT=\"$HOME/.pyenv\" && export PATH=\"$PYENV_ROOT/bin:$PATH\" && eval \"$(pyenv init -)\" && pyenv install 3.7.0 && pyenv global 3.7.0 && pip install ansible pytest testinfra pylint"]

RUN apt-get -y --purge remove git

CMD ["/usr/sbin/init"]
#RUN systemctl enable ssh.service
RUN mkdir -p /root/.ssh
ADD ./keys/id_rsa* /root/.ssh/
RUN chmod 0600 /root/.ssh/id_rsa*
RUN cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
RUN echo "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" > ~/.ssh/config

